### ISSUE TITLE
ytop is now discontinued

### ISSUE THREAD

**Issue by Titaniumtown** [grauwoelfchen/portage-overlay#1]
ytop is now discontinued, there is an alternative called bottom (https://github.com/ClementTsang/bottom) could you provide an ebuild for that maybe?

**Comment by grauwoelfchen** [comment]
Thank you so much for letting me know that. I didn't know that...
Then, instead, I'll add ClementTsang/bottom as you suggested. It looks good.

**Comment by Titaniumtown** [comment]
Happy to help!
