### ISSUE TITLE
ytop ebuild outdated, 0.6.1 -> 0.6.2

### ISSUE THREAD

**Issue by Titaniumtown** [grauwoelfchen/portage-overlay#2]
the ebuild is for ytop-0.6.1, there is a ytop 0.6.2 that released on May 16th.

**Comment by grauwoelfchen** [comment]
I'll add also the latest `0.6.2` and mark this package as masked. Thanks!

**Comment by Titaniumtown** [comment]
No problem!

**Comment by Titaniumtown** [comment]
When are you going to add the latest ytop version?

**Comment by grauwoelfchen** [comment]
Hi! At the latest, I'll try adding it til this weekend ;)

**Comment by Titaniumtown** [comment]
Ok dokie, looking forward to it! :)

**Comment by grauwoelfchen** [comment]
Fortunately, ytop `0.6.2` seems to not have any change in dependencies within Cargo.lock, so, I've just added `ytop-0.6.2.ebuild` file by https://github.com/grauwoelfchen/portage-overlay/commit/3e9fd53510365328d7cfc3b58a9058e9e46cd338, same as the one for `0.6.1`.

Comparing 0.6.1...0.6.2 · cjbassi/ytop:
https://github.com/cjbassi/ytop/compare/0.6.1...0.6.2

If you would try it when you have time, I would appreciate it. Next, I'll mask them. thank you!

**Comment by Titaniumtown** [comment]
Sorry for the late response @grauwoelfchen, thanks for bumping the version! It seems it fails to compile with LTO, so I had to disable that in the package.cflags, but either than that. Thanks!
